name: agentic-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - jupyter
  - ipykernel
  - pip:
    - langchain>=0.1.0
    - langchain-openai>=0.0.8
    - langchain-chroma>=0.1.0
    - langchain-community>=0.0.20
    - langchain-text-splitters>=0.0.1
    - google-search-results>=2.4.2
    - arxiv>=1.4.8
    - chromadb>=0.4.22
    - tiktoken>=0.5.2
    - python-dotenv>=1.0.0
    - PyPDF2>=3.0.1
    - openai>=1.0.0
    - faiss-cpu>=1.7.4
    - sentence-transformers>=2.2.2
    # Langfuse observability dependencies
    - langfuse>=2.0.0
    - opentelemetry-sdk>=1.20.0
    - opentelemetry-exporter-otlp>=1.20.0
    - openinference-instrumentation-langchain>=0.1.0